---
- name: Update the server
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes

- name: Install required system packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python-pip
    - virtualenv
    - python3-setuptools
    - unzip

- name: Uninstall AWS CLI V1
  ansible.builtin.apt:
    name: awscli
    state: absent

- name: Delete the old AWS CLI V2 temp files
  ansible.builtin.file:
    path: /tmp/aws
    state: absent

- name: Download and unzip the AWS CLI V2
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: Run the AWS CLI V2 installer
  ansible.builtin.shell: "/tmp/aws/install --update"
